"""
preview_package.py — generates out/<slug>/docker-compose.yml for local preview.

Usage:
  python scripts/workflow/preview_package.py --profile lawfirm-demo
  python scripts/workflow/preview_package.py --profile shop-demo --out out/

Steps:
  1. Run scaffold.py to produce out/<slug>/ artifacts (DDL + manifest).
     If out/<slug>/screen-manifest.json already exists, scaffold is skipped
     unless --force-scaffold is passed.
  2. Write out/<slug>/docker-compose.yml (2 services: backend + frontend).

Compose contract:
  - frontend only port exposed to host (default :8090).
  - backend reachable by frontend inside compose network as http://backend:8081.
  - PROFILE_MANIFEST mounted read-only from host into frontend container.
  - SECRET_KEY placeholder — set via env before docker compose up in production.
  - No Coolify labels / traefik config (Phase 2).

Exit codes: 0 success, 1 error.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Repo root: this file is at scripts/workflow/preview_package.py
REPO_ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Docker-compose template
# ---------------------------------------------------------------------------

_COMPOSE_TEMPLATE = """\
# docker-compose.yml — local preview for profile: {slug}
# Generated by: scripts/workflow/preview_package.py
#
# Usage:
#   docker compose -f out/{slug}/docker-compose.yml up -d --build
#   docker compose -f out/{slug}/docker-compose.yml logs -f
#   docker compose -f out/{slug}/docker-compose.yml down -v
#
# NOTE: Build context is the REPO ROOT, not this file's directory.
# Run docker compose from the repo root or use --project-directory.
#
# Ports:
#   frontend → host :{frontend_port}  (browser: http://localhost:{frontend_port}/login)
#   backend  → NOT exposed to host (internal only via compose network)

services:

  backend:
    build:
      context: {repo_root_posix}
      dockerfile: backend/adapters/fastapi/Dockerfile
    image: compounding-backend-{slug}:local
    environment:
      PORT: "8081"
      PYTHONIOENCODING: "utf-8"
    # No host port binding — frontend reaches backend inside compose network
    networks:
      - preview-net
    restart: unless-stopped

  frontend:
    build:
      context: {repo_root_posix}
      dockerfile: frontend/adapters/vanilla-htmx/Dockerfile
    image: compounding-frontend-{slug}:local
    environment:
      FRONTEND_PORT: "5000"
      BACKEND_BASE_URL: "http://backend:8081"
      CONTRACT_DIR: "/app/middle/contract"
      PROFILE_MANIFEST: "/data/manifest/screen-manifest.json"
      # SECRET_KEY: "change-me-in-production"  # set via env or secrets manager
      PYTHONIOENCODING: "utf-8"
    ports:
      - "{frontend_port}:5000"
    volumes:
      # Mount the generated manifest read-only into the container.
      # Re-run preview_package.py after scaffold changes to refresh.
      - type: bind
        source: {manifest_host_posix}
        target: /data/manifest/screen-manifest.json
        read_only: true
    depends_on:
      - backend
    networks:
      - preview-net
    restart: unless-stopped

networks:
  preview-net:
    driver: bridge
"""

# ---------------------------------------------------------------------------
# Scaffold helper
# ---------------------------------------------------------------------------

def run_scaffold(slug: str, out_root: Path) -> int:
    """Invoke scaffold.py as a subprocess. Returns exit code."""
    scaffold_script = REPO_ROOT / "scripts" / "workflow" / "scaffold.py"
    cmd = [
        sys.executable,
        str(scaffold_script),
        "--profile", slug,
        "--out", str(out_root),
    ]
    result = subprocess.run(cmd, env=_utf8_env())
    return result.returncode


def _utf8_env() -> dict:
    import os
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    return env


# ---------------------------------------------------------------------------
# Compose writer
# ---------------------------------------------------------------------------

def write_compose(slug: str, out_root: Path, frontend_port: int) -> Path:
    out_dir = out_root / slug
    manifest_host = (out_dir / "screen-manifest.json").resolve()

    compose_content = _COMPOSE_TEMPLATE.format(
        slug=slug,
        repo_root_posix=REPO_ROOT.as_posix(),
        manifest_host_posix=manifest_host.as_posix(),
        frontend_port=frontend_port,
    )

    compose_path = out_dir / "docker-compose.yml"
    compose_path.write_text(compose_content, encoding="utf-8")
    return compose_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate docker-compose.yml for local customer preview.",
    )
    parser.add_argument("--profile", required=True, help="Profile slug (e.g. lawfirm-demo)")
    parser.add_argument("--out", default=str(REPO_ROOT / "out"), help="Output root directory")
    parser.add_argument(
        "--frontend-port", type=int, default=8090,
        help="Host port for frontend (default: 8090)",
    )
    parser.add_argument(
        "--force-scaffold", action="store_true",
        help="Re-run scaffold.py even if out/<slug>/screen-manifest.json already exists.",
    )
    args = parser.parse_args()

    slug: str = args.profile
    out_root = Path(args.out).resolve()
    manifest_path = out_root / slug / "screen-manifest.json"

    # Step 1: scaffold
    if manifest_path.exists() and not args.force_scaffold:
        print(f"[preview_package] scaffold artifacts found at {out_root / slug} — skipping scaffold.")
        print(f"[preview_package] (pass --force-scaffold to regenerate)")
    else:
        print(f"[preview_package] running scaffold for profile={slug} ...")
        rc = run_scaffold(slug, out_root)
        if rc != 0:
            print("[preview_package] ERROR: scaffold.py failed — aborting.", file=sys.stderr)
            return 1
        if not manifest_path.exists():
            print(
                f"[preview_package] ERROR: scaffold succeeded but manifest not found at {manifest_path}",
                file=sys.stderr,
            )
            return 1
        print(f"[preview_package] scaffold complete. manifest → {manifest_path}")

    # Step 2: write compose
    compose_path = write_compose(slug, out_root, args.frontend_port)
    print(f"[preview_package] compose written → {compose_path}")
    print()
    print("Next steps:")
    print(f"  docker compose -f \"{compose_path}\" up -d --build")
    print(f"  # then open http://localhost:{args.frontend_port}/login")
    print(f"  docker compose -f \"{compose_path}\" down -v  # cleanup")

    return 0


if __name__ == "__main__":
    sys.exit(main())
