import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
// legal-pro theme: base tokens + navy+gold overrides + live component styles
// Generated by scripts/build-tokens.mjs from presets/themes/legal-pro/ + services/legal-rag/web/
import './tokens/tokens.gen.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter basename="/pro">
      <App />
    </BrowserRouter>
  </React.StrictMode>,
)
