/**
 * build-tokens.mjs — Bake legal-pro theme CSS into src/tokens/tokens.gen.css
 *
 * Strategy: concatenate two canonical CSS files from the preset theme directory.
 *   1. presets/themes/legal-pro/tokens.css — navy+gold custom properties (:root)
 *   2. services/legal-rag/web/styles/tokens.css — full raw+semantic token set
 *      (legal-pro/tokens.css overrides --color-primary* and --color-badge-* in :root;
 *       the live service CSS is the proven set, so we layer them correctly)
 *
 * Load order in the emitted file:
 *   1. services/legal-rag/web/styles/tokens.css  (base: grays, spacing, typography)
 *   2. presets/themes/legal-pro/tokens.css        (override: navy, gold semantic tokens)
 *
 * This avoids duplicating the full token set while keeping legal-pro as the
 * authoritative theme source (open-closed: adding a new theme only needs a
 * new tokens.css in presets/themes/<slug>/).
 *
 * Self-host rule: NO @import of external URLs. All values are inline.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..', '..', '..', '..')

const BASE_TOKENS = resolve(REPO_ROOT, 'services', 'legal-rag', 'web', 'styles', 'tokens.css')
const THEME_TOKENS = resolve(REPO_ROOT, 'presets', 'themes', 'legal-pro', 'tokens.css')
const APP_CSS = resolve(REPO_ROOT, 'services', 'legal-rag', 'web', 'styles', 'app.css')
const OUT_FILE = resolve(__dirname, '..', 'src', 'tokens', 'tokens.gen.css')

const base = readFileSync(BASE_TOKENS, 'utf8')
const theme = readFileSync(THEME_TOKENS, 'utf8')
const app = readFileSync(APP_CSS, 'utf8')

const sections = [
  '/* Auto-generated by scripts/build-tokens.mjs — DO NOT EDIT MANUALLY */',
  '/* Sources:',
  ' *   1. services/legal-rag/web/styles/tokens.css  (base raw+semantic tokens)',
  ' *   2. presets/themes/legal-pro/tokens.css         (navy+gold overrides)',
  ' *   3. services/legal-rag/web/styles/app.css       (component styles)',
  ' */',
  '',
  '/* ── 1. Base tokens (legal-rag live palette) ─────────────────────────── */',
  base,
  '',
  '/* ── 2. legal-pro theme overrides (navy+gold semantic tokens) ─────────── */',
  theme,
  '',
  '/* ── 3. Component styles (legal-rag live components) ─────────────────── */',
  app,
]

const css = sections.join('\n') + '\n'
mkdirSync(dirname(OUT_FILE), { recursive: true })
writeFileSync(OUT_FILE, css, 'utf8')

console.log(`[build-tokens] Wrote ${OUT_FILE} (${css.length} bytes, ${css.split('\n').length} lines)`)
