"""
apps/intake/intake_to_profile.py — revision JSON → profiles/<slug>.draft.yaml 변환기

사용법:
  python apps/intake/intake_to_profile.py --revision <path/to/revision.json> [--out out/]
  python apps/intake/intake_to_profile.py --client-id <id> [--data-dir ./data] [--out out/]

출력:
  - profiles/<slug>.draft.yaml   : profile schema v1 키만 포함
  - stdout (또는 --out 지정 시 out/<slug>-needs-note.md): needs note markdown

규칙:
  - profile schema v1 에 존재하는 키만 profile 에 기록
  - maps_to 중 스키마 불일치 항목은 needs note 의 "추가 시그널" 섹션으로
  - value 보정: vanilla_htmx→vanilla-htmx, node_express→node-express, go_chi→go-chi
  - 비지원 값(unknown/none_new/mssql 등) → 키 생략 + needs note 기재
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# 경로 상수
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# value 보정 맵 (questions.yaml의 value → profile schema value)
# ---------------------------------------------------------------------------

FRONTEND_MAP = {
    "react": "react",
    "vue": "vue",
    "vanilla_htmx": "vanilla-htmx",
    "nexacro": "nexacro",
    "unknown": None,  # 키 생략
}

BACKEND_MAP = {
    "springboot": "springboot",
    "fastapi": "fastapi",
    "node_express": "node-express",
    "go_chi": "go-chi",
    "unknown": None,  # 키 생략
}

DIALECT_MAP = {
    "postgres": "postgres",
    "mysql": "mysql",
    "oracle": "oracle",
    "hsqldb": "hsqldb",
    # 비지원 → None (needs note 기재)
    "mssql": None,
    "none_new": None,
    "unknown": None,
}

INDUSTRY_MAP = {
    "manufacturing": "manufacturing",
    "logistics": "logistics",
    "retail": "retail",
    "finance": "finance",
    "medical": "medical",
    "legal": "legal",
    "construction": "construction",
    "education": "education",
    "service": "service",
    "public": "public",
    "generic": "generic",
}

# domains[].entities 매핑 (multiselect value → domain slug + entity names)
DOMAIN_ENTITY_MAP = {
    "customer": ("customer", ["customer", "contact", "address"]),
    "order": ("order", ["order", "order_line"]),
    "inventory": ("inventory", ["item", "stock", "warehouse"]),
    "hr": ("hr", ["employee", "department"]),
    "hr_leave": ("hr_leave", ["leave_request", "attendance"]),
    "approval": ("approval", ["approval_request", "approver"]),
    "asset": ("asset", ["asset", "maintenance"]),
    "finance_ledger": ("finance_ledger", ["ledger_entry", "cost_center"]),
    "document": ("document", ["document", "file_ref"]),
    "report": ("report", ["report_def", "report_run"]),
    "other": None,  # needs note 로
}

# ---------------------------------------------------------------------------
# slug 생성 헬퍼
# ---------------------------------------------------------------------------

def _make_slug(company: str, industry: str) -> str:
    """회사명+업종으로 ASCII slug 생성."""
    base = company if company else industry if industry else "client"
    # 한글/특수문자 → 제거, 공백→하이픈
    slug = re.sub(r"[^\w\s-]", "", base)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"[^a-zA-Z0-9-]", "", slug)
    slug = slug.strip("-").lower()
    if not slug:
        slug = "client"
    return slug[:40]  # 너무 길면 자름

# ---------------------------------------------------------------------------
# profile YAML 직렬화 (PyYAML 없이 간단한 포맷)
# ---------------------------------------------------------------------------

def _yaml_str(val) -> str:
    if val is None:
        return "null"
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    # 문자열: 특수문자 포함 시 quote
    if any(c in str(val) for c in [":", "#", "[", "]", "{", "}", "&", "*", "!", "|", ">", "'"]):
        return f'"{val}"'
    return str(val)


def _render_profile(data: dict) -> str:
    """profile dict → YAML 문자열 (최소 직렬화)."""
    lines = [
        f"# profiles/{data['customer']['slug']}.draft.yaml",
        f"# auto-generated by intake_to_profile.py — review before use",
        f"version: 1",
        "",
        "customer:",
        f"  slug: {data['customer']['slug']}",
        f"  display: {_yaml_str(data['customer']['display'])}",
        f"  status: draft",
    ]
    if data["customer"].get("contact"):
        lines.append(f"  contact: {data['customer']['contact']}")
    if data["customer"].get("industry"):
        lines.append(f"  industry: {data['customer']['industry']}")
    lines.append("")

    # stack
    lines.append("stack:")
    if data.get("stack", {}).get("frontend"):
        lines.append(f"  frontend: {data['stack']['frontend']}")
    else:
        lines.append("  frontend: null  # 미결정 — needs note 참조")
    if data.get("stack", {}).get("backend"):
        lines.append(f"  backend: {data['stack']['backend']}")
    else:
        lines.append("  backend: null   # 미결정 — needs note 참조")
    lines.append("")

    # ddl
    lines.append("ddl:")
    if data.get("ddl", {}).get("dialect"):
        lines.append(f"  dialect: {data['ddl']['dialect']}")
    else:
        lines.append("  dialect: postgres  # 기본 권장 — 확인 필요")
    lines.append(f"  schema: {data['customer']['slug']}")
    lines.append("  idempotent_strategy: on_conflict")
    lines.append("")

    # domains
    if data.get("domains"):
        lines.append("domains:")
        for d in data["domains"]:
            lines.append(f"  - slug: {d['slug']}")
            lines.append(f"    display: {_yaml_str(d['display'])}")
            lines.append(f"    entities: [{', '.join(d['entities'])}]")
            lines.append(f"    seen_at: {date.today().isoformat()}")
        lines.append("")

    # datasource 기본값
    lines.append("datasource:")
    lines.append(f"  username: ${{{data['customer']['slug'].upper().replace('-','_')}_DB_USER}}")
    lines.append(f"  password: ${{{data['customer']['slug'].upper().replace('-','_')}_DB_PASS}}")
    lines.append('  url_template: "jdbc:postgresql://{host}:{port}/{db}"')
    lines.append("  host: db.internal")
    lines.append("  port: 5432")
    lines.append(f"  db: {data['customer']['slug'].replace('-','_')}_prod")
    lines.append("")

    # overlay 기본값
    lines.append("overlay:")
    lines.append(f"  shell_app_id: {data['customer']['slug']}-portal")
    lines.append("  vault_agent: false")
    lines.append("  sso_keycloak: false")
    lines.append("")

    # defaults
    lines.append("defaults:")
    lines.append("  locale: ko-KR")
    lines.append("  timezone: Asia/Seoul")
    lines.append("")

    # billing
    lines.append("billing:")
    lines.append("  llm_budget_usd_per_month: 100")
    lines.append("  prepaid_credits_usd: 0")
    lines.append("")

    return "\n".join(lines)

# ---------------------------------------------------------------------------
# needs note 렌더링
# ---------------------------------------------------------------------------

def _render_needs_note(slug: str, answers: dict, extra_signals: list[str]) -> str:
    """needs note markdown 생성."""
    lines = [
        f"# Needs Note — {slug}",
        f"",
        f"> intake_to_profile.py 자동 생성. 담당자 검토 후 수정.",
        f"",
        f"## 의뢰인 기본",
        f"",
        f"- **이메일**: {answers.get('contact_email', '—')}",
        f"- **연락처**: {answers.get('contact_phone', '—')}",
        f"- **회사**: {answers.get('company_name', '—')}",
        f"- **업종**: {answers.get('industry', '—')}",
        f"- **역할**: {answers.get('persona_role', '—')}",
        f"",
        f"## 누가 (Who)",
        f"",
    ]

    # 사용자 수 (ceo)
    user_count = answers.get("ceo_user_count", "")
    lines.append(f"- 예상 사용자 수: {user_count or '—'}")
    lines.append(f"- 연락 편한 시간: {answers.get('contact_preferred_time', '—')}")
    lines.append("")

    lines += [
        f"## 무엇을 (What)",
        f"",
        f"- 관리하고 싶은 데이터: {', '.join(answers.get('data_domains', [])) or '—'}",
        f"- 기타 데이터 항목: {answers.get('other_data_domains', '—') or '—'}",
        f"",
    ]

    # 페르소나별 pain
    pain = (
        answers.get("ceo_pain_bottleneck")
        or answers.get("staff_daily_pain")
        or answers.get("it_external_integration")
        or ""
    )
    lines.append(f"### 주요 페인포인트")
    lines.append(f"")
    lines.append(f"{pain or '—'}")
    lines.append("")

    lines += [
        f"## 왜 (Why)",
        f"",
        f"- CEO 성공 기준: {answers.get('ceo_success_criteria', '—') or '—'}",
        f"- 직원 한 가지 소원: {answers.get('staff_one_click_wish', '—') or '—'}",
        f"- 자유 메모: {answers.get('free_notes', '—') or '—'}",
        f"",
        f"## 현재 (Current)",
        f"",
        f"- 현재 도구: {answers.get('existing_system', '—')}",
        f"- 직원 현황 도구: {answers.get('staff_workaround_tool', '—') or '—'}",
        f"- 반드시 유지할 것: {answers.get('staff_must_keep', '—') or '—'}",
        f"",
        f"## 빈도 (Frequency)",
        f"",
        f"- 병목 발생 빈도: {answers.get('ceo_pain_frequency', '—') or '—'}",
        f"- 결재 필요 여부: {answers.get('staff_approval_needed', '—') or '—'}",
        f"- 결재 지연 경험: {answers.get('staff_approval_delay', '—') or '—'}",
        f"",
        f"## 비용·리스크 (Cost of Pain)",
        f"",
        f"- 문제 미해결 비용: {answers.get('ceo_cost_of_pain', '—') or '—'}",
        f"- 버전 혼란 경험: {answers.get('staff_sharing_pain', '—') or '—'}",
        f"",
    ]

    if extra_signals:
        lines += [
            f"## 추가 시그널 (profile schema 외 항목)",
            f"",
        ]
        for sig in extra_signals:
            lines.append(f"- {sig}")
        lines.append("")

    lines += [
        f"## IT 기술 메모",
        f"",
        f"- 서버 환경: {answers.get('it_server_env', '—') or '—'}",
        f"- Docker 가능 여부: {answers.get('it_docker_available', '—') or '—'}",
        f"- 외부 연동: {answers.get('it_external_integration', '—') or '—'}",
        f"- 추가 기술 메모: {answers.get('it_additional_notes', '—') or '—'}",
        f"",
    ]

    return "\n".join(lines)

# ---------------------------------------------------------------------------
# answers 정규화 (기존 저장분 bool 역직렬화 방어)
# ---------------------------------------------------------------------------

def _normalize_answers(answers: dict) -> dict:
    """revision JSON 의 bool/str bool 값을 yes/no str 로 정규화.

    YAML 1.1 파싱 결함으로 저장된 True/False (bool) 또는
    "True"/"False" (str) 를 "yes"/"no" 로 변환한다.
    multiselect 리스트 내부도 동일 처리.
    """
    _BOOL_STR_MAP = {"True": "yes", "False": "no", "true": "yes", "false": "no"}

    def _fix(v: object) -> object:
        if isinstance(v, bool):
            return "yes" if v else "no"
        if isinstance(v, str) and v in _BOOL_STR_MAP:
            return _BOOL_STR_MAP[v]
        return v

    result = {}
    for k, v in answers.items():
        if isinstance(v, list):
            result[k] = [_fix(item) for item in v]
        else:
            result[k] = _fix(v)
    return result


# ---------------------------------------------------------------------------
# 변환 메인 로직
# ---------------------------------------------------------------------------

def convert(answers: dict) -> tuple[dict, list[str]]:
    """answers dict → (profile_data, extra_signals_for_needs_note)."""
    # 기존 저장분 bool 파싱 결함 정규화
    answers = _normalize_answers(answers)

    extra_signals: list[str] = []

    # 기본 정보
    company = answers.get("company_name", "").strip()
    industry_raw = answers.get("industry", "")
    industry = INDUSTRY_MAP.get(industry_raw, "generic")
    email = answers.get("contact_email", "").strip()

    slug = _make_slug(company, industry_raw)

    profile: dict = {
        "customer": {
            "slug": slug,
            "display": company or slug,
            "contact": email,
            "industry": industry,
        },
        "stack": {},
        "ddl": {},
        "domains": [],
    }

    # stack.frontend
    fe_raw = answers.get("it_frontend_pref", "")
    fe_mapped = FRONTEND_MAP.get(fe_raw)
    if fe_raw and fe_raw not in (None, "unknown", ""):
        if fe_mapped:
            profile["stack"]["frontend"] = fe_mapped
        else:
            extra_signals.append(f"stack.frontend 요청값: `{fe_raw}` — profile schema 미지원, 수동 확인 필요")

    # stack.backend
    be_raw = answers.get("it_backend_pref", "")
    be_mapped = BACKEND_MAP.get(be_raw)
    if be_raw and be_raw not in (None, "unknown", ""):
        if be_mapped:
            profile["stack"]["backend"] = be_mapped
        else:
            extra_signals.append(f"stack.backend 요청값: `{be_raw}` — profile schema 미지원, 수동 확인 필요")

    # ddl.dialect
    dialect_raw = answers.get("it_db_dialect", "")
    dialect_mapped = DIALECT_MAP.get(dialect_raw)
    if dialect_raw and dialect_raw not in (None, "unknown", ""):
        if dialect_mapped:
            profile["ddl"]["dialect"] = dialect_mapped
        else:
            extra_signals.append(
                f"ddl.dialect 요청값: `{dialect_raw}` — profile schema 미지원 (mssql/none_new 등). "
                f"수동으로 지원 dialect 확인 후 설정 필요."
            )

    # domains[].entities
    data_domains = answers.get("data_domains", [])
    today = date.today().isoformat()
    for d in data_domains:
        mapping = DOMAIN_ENTITY_MAP.get(d)
        if mapping is None:
            extra_signals.append(f"domains 요청: `{d}` — 카탈로그 없음, 담당자 수동 등록 필요")
            continue
        domain_slug, entities = mapping
        profile["domains"].append({
            "slug": domain_slug,
            "display": d,
            "entities": entities,
        })

    # 스키마 불일치 항목들 → extra_signals (profile에 넣지 않음)

    # billing.setup_cost_krw (questions에 있지만 profile schema에 없음)
    budget = answers.get("ceo_budget_setup", "")
    if budget and budget != "unknown":
        extra_signals.append(f"예산 범위: `{budget}` (billing.setup_cost_krw — profile schema v1 미정의, needs note 기재)")

    # datasource.self_host_required (스키마에 없는 형태)
    data_security = answers.get("ceo_data_security", "")
    if data_security and data_security != "unknown":
        extra_signals.append(
            f"데이터 보관 요건: `{data_security}` "
            f"(datasource.self_host_required 유사 — profile schema v1 해당 키 미정의, "
            f"인도 전 CISO 리뷰 시 활용)"
        )

    # datasource.host (it_server_env → 서버환경 radio, 직접 profile에 넣지 않음)
    server_env = answers.get("it_server_env", "")
    if server_env and server_env not in ("unknown", ""):
        extra_signals.append(
            f"서버 환경: `{server_env}` "
            f"(datasource.host 참고용 — 인도 시 실제 host/ip로 교체 필요)"
        )

    # overlay.sso_keycloak (auth_method → simple/sso/ldap)
    auth = answers.get("it_auth_method", "")
    if auth and auth != "unknown":
        if auth == "simple_session":
            extra_signals.append("인증: 단순 세션 로그인 (overlay.sso_keycloak=false 권장)")
        elif auth in ("sso_keycloak", "ldap"):
            extra_signals.append(
                f"인증: `{auth}` (overlay.sso_keycloak — M3 ops pack 기능, 인도 시 별도 설정)"
            )

    # overlay.vault_agent (docker_available)
    docker = answers.get("it_docker_available", "")
    if docker and docker != "unknown":
        extra_signals.append(
            f"Docker 가용성: `{docker}` "
            f"(overlay.vault_agent 연관 — M3 ops pack. 현재 false 기본값 유지)"
        )

    return profile, extra_signals

# ---------------------------------------------------------------------------
# 진입점
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="intake revision JSON → profiles/<slug>.draft.yaml + needs note",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--revision", help="revision JSON 파일 경로")
    group.add_argument("--client-id", help="client_id (data-dir에서 최신 revision 사용)")

    parser.add_argument(
        "--data-dir",
        default=str(Path(__file__).parent / "data"),
        help="DATA_DIR (기본: apps/intake/data)",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="출력 디렉터리 (기본: profiles/ 에 draft.yaml, stdout 에 needs note)",
    )
    args = parser.parse_args()

    # answers 로드
    if args.revision:
        rev_path = Path(args.revision)
        if not rev_path.exists():
            print(f"[intake_to_profile] ERROR: {rev_path} 없음", file=sys.stderr)
            return 1
        with open(rev_path, encoding="utf-8") as f:
            answers = json.load(f)
    else:
        # client-id 모드: 최신 revision 사용
        data_dir = Path(args.data_dir)
        rev_dir = data_dir / "clients" / args.client_id / "revisions"
        if not rev_dir.exists():
            print(f"[intake_to_profile] ERROR: revisions dir 없음: {rev_dir}", file=sys.stderr)
            return 1
        rev_files = sorted(rev_dir.glob("*.json"))
        if not rev_files:
            print(f"[intake_to_profile] ERROR: revision 없음", file=sys.stderr)
            return 1
        with open(rev_files[-1], encoding="utf-8") as f:
            answers = json.load(f)

    # 변환
    profile_data, extra_signals = convert(answers)
    slug = profile_data["customer"]["slug"]

    # profile YAML 저장
    profile_yaml = _render_profile(profile_data)
    if args.out:
        out_dir = Path(args.out)
        out_dir.mkdir(parents=True, exist_ok=True)
        profile_path = out_dir / f"{slug}.draft.yaml"
    else:
        profile_path = REPO_ROOT / "profiles" / f"{slug}.draft.yaml"

    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(profile_yaml, encoding="utf-8")
    print(f"[intake_to_profile] profile 저장: {profile_path}")

    # needs note 출력/저장
    needs_note = _render_needs_note(slug, answers, extra_signals)
    if args.out:
        note_path = Path(args.out) / f"{slug}-needs-note.md"
        note_path.write_text(needs_note, encoding="utf-8")
        print(f"[intake_to_profile] needs note 저장: {note_path}")
    else:
        print("\n" + "=" * 60)
        print(needs_note)

    return 0


if __name__ == "__main__":
    sys.exit(main())
